version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  install:
    runtime-versions:
      docker: 18
      nodejs: 12
  build:
    commands:
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_REGION
      - echo $IMAGE_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
      - npm ci
      - npm run test
      - echo Build started on `date`
      - npm run build
      - docker build . -t $IMAGE_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG -t $IMAGE_REPO_URL/$IMAGE_REPO_NAME:latest
      - echo Build completed on `date`
  post_build:
    commands:
      - docker push $IMAGE_REPO_URL/$IMAGE_REPO_NAME
      - echo Writing image definitions file...
      - printf '[{"imageUri":"%s"}]' $IMAGE_REPO_URL/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json
      - deployspec.yml